config/routes.rb
Rails.application.routes.draw do
  resources :domains
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord

  after_create :setup

  def setup
    create_mysql_user
    create_env_file
    create_docker_file
    run_docker
  end

  def create_mysql_user
    require 'mysql2'

    db_host = "localhost"
    db_user = "root"
    db_pass = "toor"

    client = Mysql2::Client.new(:host => db_host, :username => db_user, :password => db_pass)
    client.query("GRANT ALL PRIVILEGES ON *.* TO '#{name}'@'localhost' IDENTIFIED BY '#{name}'")
    client.close

    client2 = Mysql2::Client.new(:host => db_host, :username => name, :password => name)
    client2.query("CREATE DATABASE #{name}")
    client2.close
  end

  def create_env_file
    File.open("./tmp/#{name}.env", 'w') do |f|
      f << "WA_DB_ENGINE=MYSQL\n"
      f << "WA_DB_HOSTNAME=#{name}\n"
      f << "WA_DB_PORT=3306\n"
      f << "WA_DB_USERNAME=#{name}\n"
      f << "WA_DB_PASSWORD=#{name}"
    end
  end

  def create_docker_file
    File.open("./tmp/#{name}.docker-compose.yml", 'w') do |f|
      f << {
        "version" =>'3',
        "services" => {
          "test" => {
            "image" => 'tutum/hello-world',
            "labels" => {
              "traefik.frontend.rule" => "Host:#{name}.wamanager.com",
              "traefik.backend" => name}
          }
        }
      }.to_yaml
    end
  end

  def run_docker
    `docker-compose -f ./tmp/#{name}.docker-compose.yml -p #{name} up -d`
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_with(model: domain, local: true) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Domains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wamanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>